- name: Ejecucion del update
  apt:
      update_cache: yes
      state: latest
      become: true
      when: ansible_os_family == "Debian"
- name: Actualizar servidores
  apt:
      name: "*"
      state: latest
      become: true
      when: ansible_os_family == "Debian"
